# Visualizing Nepal Stock Exchange Data Using Streamlit on Heroku

## Disclaimer
The contents in this blog does not recommend the scraping and this is for only educational purpose.

## Introduction
If you are from Nepal then you already know what Nepal Stock Exchange means. Honestly I don't know how to describe stock market but after watching movie [Pi](https://en.wikipedia.org/wiki/Pi_(film)), I wanted to take a look at NEPSE data by myself. I am not sure about how old data are present on the NEPSE but I think there are data available from 1980. I started to scrap data on 2019 January and it was very difficult task for me to write the right codes. But there are great and kind programmers who shares their great skills on GitHub. So I came across this [repository](https://github.com/rojesh-shikhrakar/NepseCrawler). I started to scrap all the data of past transaction and it was quite frustrating after server hanged up so I found the best way of scrapping is by scrapping data by each year and then write it on CSV file. Please follow [this mine repository](https://github.com/q-viper/NEPSE-Data-Analysis) for more scrapping code but note that **We don't use any of those data so just look that repository for more information only (if available).**  And rest is on this blog.

[Here is a demo Heroku app that we will be building](https://nepse-data-visualizer.herokuapp.com/).

<figure>
<video src = "Assets/streamlit_nepse.webm" width="100%" controls autoplay loop> </video>
<figcaption style = "text-align:left; font-style:italic">Demo</figcaption>
</figure>


## Getting Systems Ready
Of course we need python along with few other libraries. If you are wondering what should be the requirements then please follow the [repository and download](https://github.com/q-viper/NEPSE-Data-Visualizer-with-Streamlit/) all the codes then TADAAAAA!!!! But to describe it on steps, please follow below steps:
* Make a virtual environment using [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/)
* Install below libraries best way to download is using `pip install -r requirements.txt`(Assuming that you have downloaded my repository above):
    ```bash
    beautifulsoup4==4.8.0
    numpy==1.17.3
    pandas==0.25.1
    plotly==4.12.0
    requests==2.18.4
    requests-oauthlib==1.2.0
    requests-toolbelt==0.9.1
    retrying==1.3.3
    streamlit==0.71.0
    urllib3==1.22
    uvicorn==0.12.2
    matplotlib==3.3.3
    html5lib==1.0.1
    lxml==4.4.1
    ```

## Importing Dependencies
Make a python file `nepse.py` under your project folder.

```python
import streamlit as st
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup as BS
import requests
import urllib3
import time
import matplotlib.pyplot as plt
import plotly.express as px

```
* `streamlit` is used to make a web app and honestly this is the most easiest, fastest and awesome way of deploying ML APPS.
* `numpy` as usual.
* `pandas` for data processing (mostly masking, making dataframes).
* `BeautifulSoup`, we can scrap the data from NEPSE's site.
* `requests` for making HTTP requests.
* `urllib3` for handling HTTP client.
* `time` as usual.
* `matplotlib` for making simple visualization.
* `plotly` for making cool visualization.

## Method: `company_names() `
As of 2022, URLs seems to have changed, and thus old will be commented out.

In [1]:
import streamlit as st
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup as BS
import requests
import urllib3
import time
import matplotlib.pyplot as plt
import plotly.express as px

def company_names():
    http = urllib3.PoolManager()
    http.addheaders = [('User-agent', 'Mozilla/61.0')]
    # url = "http://www.nepalstock.com.np/company?_limit=500"
    url = "http://www.nepalstock.com/company?_limit=500"
    web_page = http.request('GET', url)
    soup = BS(web_page.data, 'html5lib')
    table = soup.find('table')
    company=[]
    rows = [row.findAll('td') for row in table.findAll('tr')[1:-2]]
    col = 0
    notfirstrun = False
    for row in rows:
        companydata =[]
        for data in row:
            if col == 5 and notfirstrun:
                companydata.append(data.a.get('href').split('/')[-1])
            else:
                companydata.append(data.text.strip())
            col += 1
        company.append(companydata)
        col =0
        notfirstrun = True

    df = pd.DataFrame(company[1:],columns=company[0])
    df.rename(columns={'Operations':'Symbol No'},inplace=True)
    df.index.name = "SN"
    df.drop(columns='',inplace=True)
    df.drop(columns='S.N.',inplace=True)
    return df
company_names()

,Stock Name,Stock Symbol,Sector,Symbol No
SN,,,,
0,10 % NMB DEBENTURE 2085,NMBD2085,Corporate Debenture,2850
1,10% Himalayan Bank Debenture 2083,HBLD83,Corporate Debenture,2873
2,10% Laxmi Bank Debenture 2086,LBLD86,Corporate Debenture,2879
3,10% Nabil Debenture 2082,NBLD82,Corporate Debenture,2892
4,10% Nepal SBI Bank Debenture 2086,SBIBD86,Corporate Debenture,2890
...,...,...,...,...
320,Unnati Sahakarya Laghubitta Bittiya Sanstha Li...,USLB,Microfinance,2774
321,Upper Tamakoshi Hydropower Ltd,UPPER,Hydro Power,2792
322,Vijaya laghubitta Bittiya Sanstha Ltd.,VLBS,Microfinance,687
323,Wean Nepal Laghubitta Bittiya Sanstha Limited,WNLB,Microfinance,2781
324,Womi Microfinance Bittiya Sanstha Ltd.,WOMI,Microfinance,706

This method is used to get list of company names. 
* Create a HTTP client and make a GET request.
* Find the table of result from http://www.nepalstock.com/company?_limit=500
* Do some cleaning to get the company data for each company and make a DataFrame for it.

After calling the method above, a dataframe just like above must be shown.
It is clear that there are ~273~ 325 companies. We will be using columns like Stock Symbol and Symbol No.

## Visualising Only Limited Data on Streamlit
Why to show entire dataframe on webapp while we can show only desired? So we will be using iloc on dataframe i.e. slicing on index.

In [2]:
# @st.cache(suppress_st_warning=True)
def load_data():
    # data = pd.read_csv(DATA_URL, nrows=nrows)
    data = company_names()
    
    lowercase = lambda x: str(x).lower()
    data.rename(lowercase, axis='columns', inplace=True)
    return data

st.subheader("View the list of Companies.")
def view_company_names():
    st.markdown("(Base URL is [http://www.nepalstock.com/company?_limit=500](http://www.nepalstock.com/company?_limit=500))")
    num = st.number_input("Enter how many records to view?", min_value=1, max_value=None, step=1)
    data_load_state = st.text('Loading data...')
    data = load_data()
    data_load_state.text("Done! (using st.cache)")
    if st.checkbox('Show raw data'):
        st.subheader('Raw data')
        st.write(data.iloc[:num])
    return data

cdf = view_company_names()
cdf

,stock name,stock symbol,sector,symbol no
SN,,,,
0,10 % NMB DEBENTURE 2085,NMBD2085,Corporate Debenture,2850
1,10% Himalayan Bank Debenture 2083,HBLD83,Corporate Debenture,2873
2,10% Laxmi Bank Debenture 2086,LBLD86,Corporate Debenture,2879
3,10% Nabil Debenture 2082,NBLD82,Corporate Debenture,2892
4,10% Nepal SBI Bank Debenture 2086,SBIBD86,Corporate Debenture,2890
...,...,...,...,...
320,Unnati Sahakarya Laghubitta Bittiya Sanstha Li...,USLB,Microfinance,2774
321,Upper Tamakoshi Hydropower Ltd,UPPER,Hydro Power,2792
322,Vijaya laghubitta Bittiya Sanstha Ltd.,VLBS,Microfinance,687
323,Wean Nepal Laghubitta Bittiya Sanstha Limited,WNLB,Microfinance,2781
324,Womi Microfinance Bittiya Sanstha Ltd.,WOMI,Microfinance,706

2 methods are given above. 

### Method `load_data()`
This method uses the decorator `cache` to store data in cache and to ignore the cache warning, `suppress_st_warning=True` is used. This method calls the method `comapny_names()` and gets the dataframe then makes all the column name to lowercase and then returns that dataframe. 

### Method `view_company_names()`
This method is for visualizing actual data. It allows us to input the number and then the dataframe is sliced up to that index. 
* Streamlit allows us to take number input using `number_input()` method.
* streamlit allows us to show text usign `text()` method.
* Then we load our data from previous method and then after data has been loaded, show log like text.
* streamlit allows us to use checkbox using `checkbox()` then if it is ticked then show data up to the number user has entered.
* Also return the original data because it will be used later.

Now save the code above and then from terminal opening on same directory as this file(assume that file name is neplse.py), do
```bash
streamlit run nepse.py
```

If everything is okay then streamlit will provide us a local link with unique port number. By clicking it, we can visualize our first ever NEPSE data visualizer. It should look like below.
![image](Assets/custom_df.png)

## View Company Details

In [3]:
st.subheader("View Company Details.")
def view_company_details():
    symbol = st.text_input("Enter Stock Symbol. (For Reference, see above record table.)")
    symbol_no = None
    if len(symbol)>=2:
        url = "http://www.nepalstock.com/company/"
        
        try:
            req = requests.post(url, data={"stock_symbol":symbol}, verify=False)
            symbol_no = cdf[cdf["stock symbol"]==symbol]["symbol no"]
        except requests.exceptions.RequestException as e:
            print(e)

        response = req.text
        soup = BS(response, "lxml")
        table = soup.find("table")
        
        for row in table.findAll("tr")[4:]:
            col = row.findAll("td")
            st.write(col[0].string,": ",col[1].string)
        
    return symbol_no

symbol_no = view_company_details()
if  symbol_no is not None:
    symbol_no = symbol_no.tolist()[0]

The method above is used to visualize the company details. 
* Ask user for the Stock Symbol (ex NMB, ADBL etc).
* Same as earlier method, it makes post request to url http://www.nepalstock.com/company/ and then uses that result to view details.
* If the Stock Symbol matches then get symbol number assigned to it. Then do some data cleaning and visualize the result by `st.write()`
* Return the Symbol Number.

The result must be something like below.
![img](Assets/company_detail.png)

## Visualize Data of some time period
First we need to get that data. As I stated earlier, sometimes scraping data of entire history will not be feasible and last time I tried that, my laptop crashed so scrapping part by part will be great idea.


### Method: `CompanyStocksTransactions`
* Make a GET request to ~http://www.nepalstock.com.np/company/transactions/%s/0/?startDate=%s&endDate=%s&_limit=9000000~ http://www.nepalstock.com/company/transactions/%s/0/?startDate=%s&endDate=%s&_limit=9000000 by providing start and end date in required field.
* Then as previous methods, clean the data and make a dataframe.
* Return that dataframe.

### Method: `view_by_year`
* Method takes start date, end date and symbol number of that company symbol.
* Call the method `CompanyStocksTransactions` to get dataframe within that date.
* Return that dataframe.

**Before calling methods, we try to get date from the streamlit's `date_input` method and then pass that date to `view_by_year` method.** Also make a checkbox whether to see raw dataframe or not.

In [4]:
st.subheader("Check Company's Progress in Years")
def CompanyStocksTransactions(SymbolNo,startDate, endDate):
    FloorSheet = []
    limit=20000
    page_no = 1   
    header = []

    while True:
        http = urllib3.PoolManager()
        http.addheaders = [('User-agent', 'Mozilla/61.0')]
        url = "http://www.nepalstock.com/company/transactions/%s/%s/?startDate=%s&endDate=%s&_limit=%s"%(SymbolNo,page_no,
                                                                                                            startDate,endDate,
                                                                                                         limit)
        print("Current URL: ", url)

        web_page = http.request('GET',url)
        soup = BS(web_page.data, 'html5lib')
        table = soup.find('table')
        rows = [row.findAll('td') for row in table.findAll('tr')[1:-2]]
        
        print(f"Found {len(rows)} rows.")
        if len(rows)>= 1:
            if len(header)==0:
                header = [data.text.strip() for data in rows[0]]
                rows = rows[1:]
            else:
                rows=rows[1:]
            for row in rows:
                rd = [data.text.strip() for data in row]
                FloorSheet.append(rd)
            #print(rd[1])
            print("")

        else:
            break
        if len(rows)+1!=limit:
            print("Full")
            break
        else:
            page_no+=1


    # FloorSheet.insert(0, header) 
    if(len(FloorSheet) != 0):
        FloorSheetdf = pd.DataFrame(FloorSheet[1:],columns=header)
        FloorSheetdf['Date']=pd.to_datetime(FloorSheetdf['Contract No'], format='%Y%m%d%H%M%f', errors='ignore')
        
        return (1, FloorSheetdf)
    else:
        return (0, None)

def CompanyStocksTransactions(SymbolNo,startDate, endDate):
    url="http://www.nepalstock.com.np/company/transactions/%s/0/?startDate=%s&endDate=%s&_limit=10000"%(SymbolNo,startDate, endDate)
    print("Connecting to %s "%url)
    http = urllib3.PoolManager()
    http.addheaders = [('User-agent', 'Mozilla/61.0')]
    web_page = http.request('GET',url)
    #print("Adding to DataFrame")
    soup = BS(web_page.data, 'html5lib')
    table = soup.find('table')
    if table:
        FloorSheet=[]
        rows = [row.findAll('td') for row in table.findAll('tr')[1:-2]]
        for row in rows:
              FloorSheet.append([data.text.strip() for data in row])
        if(len(FloorSheet) != 0):
              FloorSheetdf = pd.DataFrame(FloorSheet[1:],columns=FloorSheet[0])
              FloorSheetdf['Date']=pd.to_datetime(FloorSheetdf['Contract No'], format='%Y%m%d%H%M%f', errors='ignore')
              return (1, FloorSheetdf)
        else:
              return (0, None)
    else:
        return (0, None)

# @st.cache(suppress_st_warning=True)    
def view_by_year(start_date="2020-1-1", end_date="2020-1-2", symbol="2810"):
    st.write("From year %s to %s "%(start_date, end_date))
    
    success, dftest=CompanyStocksTransactions(symbol, start_date, end_date)
    if success==1:
        st.write("Successfully scrapped data. Showing results.")
        # st.write(dftest)
    else:
        st.write("Can't scrap data. Try using another symbol. Or Another date.")
    return dftest
# start_date = st.date_input("Please input start date.")
# end_date = st.date_input("Please input end date.", min_value=start_date)
# dfyear = view_by_year(start_date=str(start_date), end_date=str(end_date), symbol=symbol_no)
# show_df = st.checkbox("Show Data")

# if show_df:
#     st.write(dfyear)
df = view_by_year("2020-10-30", "2021-1-2", symbol="2850") #2810
df

2022-02-28 23:36:39.046 INFO    urllib3.poolmanager: Redirecting http://www.nepalstock.com.np/company/transactions/2850/0/?startDate=2020-10-30&endDate=2021-1-2&_limit=10000 -> https://www.nepalstock.com.np

Connecting to http://www.nepalstock.com.np/company/transactions/2850/0/?startDate=2020-10-30&endDate=2021-1-2&_limit=10000

In [7]:
def CompanyStocksTransactions(SymbolNo,startDate, endDate):
    FloorSheet = []
    limit=20000
    page_no = 1   
    header = []

    while True:
        http = urllib3.PoolManager()
        http.addheaders = [('User-agent', 'Mozilla/61.0')]
        url = "http://www.nepalstock.com/company/transactions/%s/%s/?startDate=%s&endDate=%s&_limit=%s"%(SymbolNo,page_no,
                                                                                                            startDate,endDate,
                                                                                                         limit)
        print("Current URL: ", url)

        web_page = http.request('GET',url)
        soup = BS(web_page.data, 'html5lib')
        table = soup.find('table')
        rows = [row.findAll('td') for row in table.findAll('tr')[1:-2]]
        
        print(f"Found {len(rows)} rows.")
        if len(rows)>= 1:
            if len(header)==0:
                header = [data.text.strip() for data in rows[0]]
                rows = rows[1:]
            else:
                rows=rows[1:]
            for row in rows:
                rd = [data.text.strip() for data in row]
                FloorSheet.append(rd)
            #print(rd[1])
            print("")

        else:
            break
        if len(rows)+1!=limit:
            print("Full")
            break
        else:
            page_no+=1


    # FloorSheet.insert(0, header) 
    if(len(FloorSheet) != 0):
        FloorSheetdf = pd.DataFrame(FloorSheet[1:],columns=header)
        FloorSheetdf['Date']=pd.to_datetime(FloorSheetdf['Contract No'], format='%Y%m%d%H%M%f', errors='ignore')
        
        return FloorSheetdf
    else:
        return None
CompanyStocksTransactions("131", "2019-10-30", "2019-11-02")
# start_date = "2010-10-30"
# end_date = "2021-1-2"
# SymbolNo = 2850
# endDate = end_date
# # cd = pd.to_datetime(df.iloc[0].Date).date()
# # print(start_date, str(cd), start_date<str(cd))
# FloorSheet = []
# limit=10000
# page_no = 1   
# header = []

# while True:
#     http = urllib3.PoolManager()
#     http.addheaders = [('User-agent', 'Mozilla/61.0')]
#     url = "http://www.nepalstock.com.np/company/transactions/%s/%s/?startDate=%s&endDate=%s&_limit=%s"%(SymbolNo,page_no,
#                                                                                                         start_date,end_date,
#                                                                                                         limit)
#     print(url)
    
#     web_page = http.request('GET',url)
#     soup = BS(web_page.data, 'html5lib')
#     table = soup.find('table')
#     rows = [row.findAll('td') for row in table.findAll('tr')[1:-2]]
    
#     print(f"Found {len(rows)} rows.")
#     if len(rows)>= 1:
#         if len(header)==0:
#             header = rows[0]
#         else:
#             rows=rows[1:]

    
#         for row in rows:
#             rd = [data.text.strip() for data in row]
#             FloorSheet.append(rd)
#         print(rd[1])
#         print("")
        
#     else:
#         break
#     if len(rows)!=limit:
#         break
#     else:
#         page_no+=1
        
        
# # FloorSheet.insert(0, header) 
# if(len(FloorSheet) != 0):
#     FloorSheetdf = pd.DataFrame(FloorSheet[1:],columns=FloorSheet[0])
#     FloorSheetdf['Date']=pd.to_datetime(FloorSheetdf['Contract No'], format='%Y%m%d%H%M%f', errors='ignore')
# FloorSheetdf

Current URL:  http://www.nepalstock.com/company/transactions/131/1/?startDate=2019-10-30&endDate=2019-11-02&_limit=20000
Found 62 rows.

Full

   S.N.       Contract No Stock Symbol Buyer Broker Seller Broker Quantity  \
0     2  2019103101003542        NABIL           25            58       60
1     3  2019103101003563        NABIL           58            34       10
2     4  2019103101003511        NABIL           45            58       15
3     5  2019103101003342        NABIL           13            58       70
4     6  2019103101003346        NABIL           49            58      284
5     7  2019103101003240        NABIL           25            26       40
6     8  2019103101003196        NABIL            7            19      144
7     9  2019103101003179        NABIL           19            58       50
8    10  2019103101003061        NABIL           49            58       35
9    11  2019103101003062        NABIL           22            58       10
10   12  2019103101003063        NABIL           39            58      100
11   13  2019103101003064        NABIL           13            58      400
12   14  2019103101003065        NABIL           29            58       15
13   15  2019103101003066        NABIL           51            58      150
14   16  2019103101003067        NABIL            3            58       50
15   17  2019103101003068        NABIL           49            58      100
16   18  2019103101003069        NABIL           11            58       50
17   19  2019103101003070        NABIL           11            58      285
18   20  2019103101003071        NABIL           25            58       50
19   21  2019103101003072        NABIL           43            58      200
20   22  2019103101003073        NABIL           48            58      100
21   23  2019103101003074        NABIL           25            58      100
22   24  2019103101003075        NABIL            8            58      500
23   25  2019103101003076        NABIL           38            58      300
24   26  2019103101003077        NABIL           39            58       80
25   27  2019103101003078        NABIL            7            58      100
26   28  2019103101003079        NABIL           17            58      200
27   29  2019103101003080        NABIL           35            58       40
28   30  2019103101003081        NABIL           38            58      100
29   31  2019103101003082        NABIL           41            58       10
30   32  2019103101002884        NABIL           49            55       15
31   33  2019103101002871        NABIL           19            45      118
32   34  2019103101002872        NABIL           49            45       50
33   35  2019103101002525        NABIL           45             6       30
34   36  2019103101002526        NABIL           19             6       82
35   37  2019103101002178        NABIL            3            26       56
36   38  2019103101002163        NABIL           22            20       50
37   39  2019103101002164        NABIL            3            20       43
38   40  2019103101002102        NABIL           35            20       10
39   41  2019103101002080        NABIL           41            20      100
40   42  2019103101001508        NABIL           19            20      500
41   43  2019103101001435        NABIL           35            20       20
42   44  2019103101001421        NABIL           44            34       28
43   45  2019103101001320        NABIL           11            40       20
44   46  2019103101001321        NABIL           22            40      200
45   47  2019103101001322        NABIL           45            40       30
46   48  2019103101001323        NABIL           34            40      200
47   49  2019103101001324        NABIL           46            40       20
48   50  2019103101001325        NABIL           49            40       50
49   51  2019103101001326        NABIL           22            40       20
50   52  2019103101001327        NABIL           17            40      100
51   53  2019103101001328        NABIL           44            40      172
52   54  2019103101001128        NABIL           47            20      200
53   55  2019103101001099        NABIL           56            20      177
54   56  2019103101000974        NABIL           19            45       10
55   57  2019103101000918        NABIL           56            39       23
56   58  2019103101000900        NABIL           17            45       50
57   59  2019103101000747        NABIL           17            21       30
58   60  2019103101000574        NABIL           42            57       57
59   61  2019103101000575        NABIL           42            48       13

   Rate     Amount                       Date
0   755   45300.00 2019-10-31 01:00:00.354200
1   761    7610.00 2019-10-31 01:00:00.356300
2   755   11325.00 2019-10-31 01:00:00.351100
3   755   52850.00 2019-10-31 01:00:00.334200
4   755  214420.00 2019-10-31 01:00:00.334600
5   754   30160.00 2019-10-31 01:00:00.324000
6   753  108432.00 2019-10-31 01:00:00.319600
7   755   37750.00 2019-10-31 01:00:00.317900
8   758   26530.00 2019-10-31 01:00:00.306100
9   757    7570.00 2019-10-31 01:00:00.306200
10  757   75700.00 2019-10-31 01:00:00.306300
11  757  302800.00 2019-10-31 01:00:00.306400
12  756   11340.00 2019-10-31 01:00:00.306500
13  756  113400.00 2019-10-31 01:00:00.306600
14  756   37800.00 2019-10-31 01:00:00.306700
15  756   75600.00 2019-10-31 01:00:00.306800
16  756   37800.00 2019-10-31 01:00:00.306900
17  756  215460.00 2019-10-31 01:00:00.307000
18  756   37800.00 2019-10-31 01:00:00.307100
19  756  151200.00 2019-10-31 01:00:00.307200
20  755   75500.00 2019-10-31 01:00:00.307300
21  755   75500.00 2019-10-31 01:00:00.307400
22  755  377500.00 2019-10-31 01:00:00.307500
23  755  226500.00 2019-10-31 01:00:00.307600
24  755   60400.00 2019-10-31 01:00:00.307700
25  755   75500.00 2019-10-31 01:00:00.307800
26  755  151000.00 2019-10-31 01:00:00.307900
27  755   30200.00 2019-10-31 01:00:00.308000
28  755   75500.00 2019-10-31 01:00:00.308100
29  755    7550.00 2019-10-31 01:00:00.308200
30  758   11370.00 2019-10-31 01:00:00.288400
31  758   89444.00 2019-10-31 01:00:00.287100
32  758   37900.00 2019-10-31 01:00:00.287200
33  758   22740.00 2019-10-31 01:00:00.252500
34  758   62156.00 2019-10-31 01:00:00.252600
35  756   42336.00 2019-10-31 01:00:00.217800
36  757   37850.00 2019-10-31 01:00:00.216300
37  756   32508.00 2019-10-31 01:00:00.216400
38  758    7580.00 2019-10-31 01:00:00.210200
39  758   75800.00 2019-10-31 01:00:00.208000
40  760  380000.00 2019-10-31 01:00:00.150800
41  760   15200.00 2019-10-31 01:00:00.143500
42  761   21308.00 2019-10-31 01:00:00.142100
43  764   15280.00 2019-10-31 01:00:00.132000
44  764  152800.00 2019-10-31 01:00:00.132100
45  764   22920.00 2019-10-31 01:00:00.132200
46  763  152600.00 2019-10-31 01:00:00.132300
47  763   15260.00 2019-10-31 01:00:00.132400
48  763   38150.00 2019-10-31 01:00:00.132500
49  762   15240.00 2019-10-31 01:00:00.132600
50  762   76200.00 2019-10-31 01:00:00.132700
51  761  130892.00 2019-10-31 01:00:00.132800
52  765  153000.00 2019-10-31 01:00:00.112800
53  765  135405.00 2019-10-31 01:00:00.109900
54  766    7660.00 2019-10-31 01:00:00.097400
55  765   17595.00 2019-10-31 01:00:00.091800
56  766   38300.00 2019-10-31 01:00:00.090000
57  765   22950.00 2019-10-31 01:00:00.074700
58  768   43776.00 2019-10-31 01:00:00.057400
59  768    9984.00 2019-10-31 01:00:00.057500

In [8]:
# cd = pd.to_datetime(cd)+pd.DateOffset(microseconds=1)
# cd = str(cd)
# cd
FloorSheetdf[FloorSheetdf["S.N."].duplicated()]

NameError: name 'FloorSheetdf' is not defined

The result must be like below:
![img](Assets/progress_year.png)

## Do Real Visualization
Now is the time for doing visualization of our time series data. We have already scrapped the data of our interest now is the time to use image to tell story.

* Prepare the checkboxes to visualize data.
    * Date vs Buyer Broker
    * Date vs Seller Broker
    * Date vs Amount
    * Date vs Rate

In [9]:
date_vs_bbroker = st.checkbox("Date Vs Buyer Broker")
date_vs_sbroker = st.checkbox("Date Vs Seller Broker")
date_vs_amount = st.checkbox("Date vs Amount")
date_vs_rate = st.checkbox("Date vs Rate")

def visualise_broker():
    if date_vs_bbroker:
        st.subheader("Date Vs Buyer Broker")
        fig = px.scatter(dfyear, x="Date", y="Buyer Broker")
        st.plotly_chart(fig)

    if date_vs_amount:
        st.subheader("Date Vs Amount")
        fig = px.scatter(dfyear, x="Date", y="Amount")
        st.plotly_chart(fig)
        
    if date_vs_sbroker:
        st.subheader("Date Vs Seller Broker")
        fig = px.scatter(dfyear, x="Date", y="Seller Broker")
        st.plotly_chart(fig)
    
    if date_vs_rate:
        st.subheader("Date Vs Rate")
        fig = px.scatter(dfyear, x="Date", y="Rate")
        st.plotly_chart(fig)

visualise_broker()

* Use plotly to scatter our data by giving dataframe and then x and y axis. 
* Use the figure made by plotly to view it on web app using streamlit's `plotly_chart`.

Our result must be like below.
![img](Assets/date_vs_buyer.png)

**If you have came this far then congratulations, you have just made your streamlit app to visualize NEPSE data. Now is the time to make it live on Heroku.**

To deploy it on Heroku, we need to have a Heroku Account. Please make one. After making an account, make a new heroku app from [here](https://dashboard.heroku.com/new-app?org=personal-apps). Give it a proper name.

## Preparing additional files
Assume that your main file name is `nepse.py`. I am not going to explain in detail but if you are concerned then please follow this blog where i have written about deploying [Face Mask Classifier on Heroku](https://q-viper.github.io/2020/10/13/deploying-face-mask-classifier-on-heroku-deploy/). Additional files required are:
* requirements.txt: Using 
    ```shell
    pip freeze > requirements.txt
    ```
* Procfile: Process file.
    ```shell
    web: sh setup.sh && streamlit run nepse.py
    ```
* setup.sh: Setup file.
    ```shell
    mkdir -p ~/.streamlit

    echo "[server]
    headless = true
    port = $PORT
    enableCORS = false
    " > ~/.streamlit/config.toml
    ```

After making all files then make one Git repository and push all the changes to it because we will be integrating our repository to Heroku and Heroku itself will process our files but beware of free version because we have limited number of build number available.

* Make sure you are selecting GitHub on Deployement Method.
![img](Assets/github_repo.png)

* Then select the repository you are using to visualize on App Connected to GitHub.
![img](Assets/repo_select.png)

* Chose the right branch.
* If you want automatic deploys, i.e re deploy whenever changes found. Using manual deploy will be best for free version.
* Click on Deploy Branch and let it finish the install dependencies and then after completing run launch the app.
* If error occurs please let me know on comment section.

## Finally
Thank you so much for reading my blog and I really hope that this blog has been some help for you too. I am always eager to meet awesome people like you so please find me on Twitter as [QuassarianViper](https://twitter.com/QuassarianViper) and LinkedIn as [Ramkrishna Acharya](https://www.linkedin.com/in/qramkrishna/).

### Why not read more?
* [Gesture Based Visually Writing System Using OpenCV and Python]({{site.url}}/2020/08/01/gesture-based-visually-writing-system-using-opencv-and-python/)
* [Gesture Based Visually Writing System: Adding Visual User Interface]({{site.url}}/2020/08/11/gesture-based-visually-writing-system-make-a-visual-user-interface/)
* [Gesture Based Visually Writing System: Adding Virtual Animationn, New Mode and New VUI]({{site.url}}/2020/08/14/gesture-based-visually-writing-system-adding-virtual-animation-new-mode-and-new-vui/)
* [Gesture Based Visually Writing System: Add Slider, More Colors and Optimized OOP code]({{site.url}}/2020/08/21/gesture-based-visually-writing-system-add-slider-more-colors-and-optimized-code/)
* [Gesture Based Visually Writing System: A Web App]({{site.url}}/2020/08/29/gesture-based-visually-writing-system-web-app/)
* [Contour Based Game: Break The Bricks]({{site.url}}/2020/08/16/contour-based-game-break-the-bricks/)
* [Linear Regression from Scratch]({{site.url}}/2020/08/07/writing-a-linear-regression-class-from-scratch-using-python/)
* [Writing Popular ML Optimizers from Scratch]({{site.url}}/2020/06/05/writing-popular-machine-learning-optimizers-from-scratch-on-python/)
* [Feed Forward Neural Network from Scratch]({{site.url}}/2020/05/31/writing-a-deep-neural-network-from-scratch-on-python/)
* [Convolutional Neural Networks from Scratch]({{site.url}}/2020/06/05/convolutional-neural-networks-from-scratch-on-python/)
* [Writing a Simple Image Processing Class from Scratch]({{site.url}}/2020/05/31/image-processing-class-from-scratch-on-python/)
* [Deploying a RASA Chatbot on Android using Unity3d]({{site.url}}/2020/08/04/deploying-a-simple-rasa-chatbot-on-unity3d-project-to-make-a-chatbot-for-android-devices/)
* [Naive Bayes for text classifications: Scratch to Framework]({{site.url}}/2020/03/04/text-classification-using-naive-bayes-scratch-to-the-framework/)
* [Simple OCR for Devanagari Handwritten Text]({{site.url}}/2020/02/25/building-ocr-for-devanagari-handwritten-character/)